export interface GeneratedQuestion {
  questionText: string;
  questionType: 'MCQ' | 'TrueFalse';
  options: string[];
  correctAnswer: number;
  explanation: string;
  bloomLevel: 'Remembering' | 'Understanding' | 'Applying' | 'Analyzing' | 'Evaluating';
  points: number;
}

export interface AIGenerateRequest {
  topic: string;
  count: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  subtopics?: string;
}

const domainKnowledge: Record<string, GeneratedQuestion[]> = {
  'operating systems': [
    {
      questionText: 'Which of the following conditions is NOT a necessary condition for a deadlock to occur?',
      questionType: 'MCQ',
      options: ['Mutual Exclusion', 'Hold and Wait', 'Preemption Allowed', 'Circular Wait'],
      correctAnswer: 2,
      explanation: 'For a deadlock to occur, "No Preemption" is necessary. If preemption is allowed, deadlocks can be resolved or prevented.',
      bloomLevel: 'Understanding',
      points: 2,
    },
    {
      questionText: 'In virtual memory management, when does a page fault occur?',
      questionType: 'MCQ',
      options: [
        'When a requested page is present in the Translation Lookaside Buffer (TLB)',
        'When the CPU tries to access a page not currently resident in main memory (RAM)',
        'When a page is corrupted on disk',
        'When the page table size exceeds physical RAM',
      ],
      correctAnswer: 1,
      explanation: 'A page fault trap is generated by the Memory Management Unit (MMU) when the valid/invalid bit indicates the referenced page is not resident in main memory.',
      bloomLevel: 'Understanding',
      points: 2,
    },
    {
      questionText: 'What is the primary advantage of the Round Robin (RR) CPU scheduling algorithm?',
      questionType: 'MCQ',
      options: [
        'Guarantees shortest average waiting time',
        'Prevents CPU starvation through time-slicing fairness',
        'Eliminates context switching overhead',
        'Prioritizes I/O bound processes automatically',
      ],
      correctAnswer: 1,
      explanation: 'Round Robin allocates a fixed quantum to each process, preventing starvation and providing fast response times in interactive time-sharing systems.',
      bloomLevel: 'Analyzing',
      points: 2,
    },
    {
      questionText: 'Which CPU scheduling algorithm is provably optimal in terms of minimizing average waiting time?',
      questionType: 'MCQ',
      options: ['First-Come First-Served (FCFS)', 'Shortest Job First (SJF)', 'Priority Scheduling', 'Multilevel Queue'],
      correctAnswer: 1,
      explanation: 'SJF (Shortest Job First) is provably optimal because moving a short process before a long process decreases the waiting time of the short process more than it increases that of the long process.',
      bloomLevel: 'Remembering',
      points: 2,
    },
    {
      questionText: 'What is the phenomenon called when increasing the number of page frames leads to an increase in the number of page faults for FIFO replacement?',
      questionType: 'MCQ',
      options: ["Belady's Anomaly", 'Thrashing', 'Starvation', 'Convoy Effect'],
      correctAnswer: 0,
      explanation: "Belady's Anomaly is a counter-intuitive phenomenon in FIFO page replacement where assigning more frames causes more page faults.",
      bloomLevel: 'Remembering',
      points: 2,
    },
    {
      questionText: 'Thrashing occurs in an operating system when:',
      questionType: 'MCQ',
      options: [
        'The CPU spends more time paging than executing instructions',
        'Two processes wait for the same mutex',
        'Disk fragmentation reaches 100%',
        'The kernel stack overflows',
      ],
      correctAnswer: 0,
      explanation: 'Thrashing occurs when high degree of multiprogramming causes processes to constantly page fault, causing the CPU utilization to plunge.',
      bloomLevel: 'Applying',
      points: 2,
    },
  ],
  'computer networks': [
    {
      questionText: 'Which transport layer protocol provides connection-oriented, reliable, and byte-stream delivery with congestion control?',
      questionType: 'MCQ',
      options: ['UDP (User Datagram Protocol)', 'TCP (Transmission Control Protocol)', 'ICMP', 'IP'],
      correctAnswer: 1,
      explanation: 'TCP guarantees in-order reliable packet transmission using three-way handshakes, sequence numbers, checksums, and congestion window algorithms.',
      bloomLevel: 'Remembering',
      points: 2,
    },
    {
      questionText: 'In the OSI model, which layer is responsible for logical IP addressing and path routing across multiple subnets?',
      questionType: 'MCQ',
      options: ['Data Link Layer', 'Network Layer', 'Transport Layer', 'Session Layer'],
      correctAnswer: 1,
      explanation: 'The Network layer (Layer 3) handles IP packet encapsulation, addressing, and routing decisions across networks.',
      bloomLevel: 'Understanding',
      points: 2,
    },
    {
      questionText: 'What is the purpose of the Address Resolution Protocol (ARP)?',
      questionType: 'MCQ',
      options: [
        'Translating IP addresses to MAC hardware addresses',
        'Translating Domain names into IP addresses',
        'Assigning dynamic IP addresses automatically',
        'Encrypting payloads across WAN connections',
      ],
      correctAnswer: 0,
      explanation: 'ARP maps an IPv4 network address to a physical Data Link layer MAC address within a local broadcast domain.',
      bloomLevel: 'Applying',
      points: 2,
    },
    {
      questionText: 'Which protocol utilizes a 3-way handshake (SYN, SYN-ACK, ACK) to establish connections?',
      questionType: 'MCQ',
      options: ['HTTP/1.0 over UDP', 'Transmission Control Protocol (TCP)', 'DNS Query', 'BGP Routing Protocol'],
      correctAnswer: 1,
      explanation: 'TCP uses SYN, SYN-ACK, and ACK flags to synchronize sequence numbers and acknowledge connection establishment.',
      bloomLevel: 'Understanding',
      points: 2,
    },
  ],
  'database': [
    {
      questionText: 'Which normal form eliminates partial functional dependencies on a composite primary key?',
      questionType: 'MCQ',
      options: ['1NF (First Normal Form)', '2NF (Second Normal Form)', '3NF (Third Normal Form)', 'BCNF (Boyce-Codd Normal Form)'],
      correctAnswer: 1,
      explanation: 'A relation is in 2NF if it is in 1NF and every non-prime attribute is fully functionally dependent on the entire candidate key (no partial dependency).',
      bloomLevel: 'Understanding',
      points: 2,
    },
    {
      questionText: 'In database ACID properties, which property ensures that transactions execute without interference from concurrent transactions?',
      questionType: 'MCQ',
      options: ['Atomicity', 'Consistency', 'Isolation', 'Durability'],
      correctAnswer: 2,
      explanation: 'Isolation ensures that multiple concurrent transactions execute independently and do not observe uncommitted intermediate states.',
      bloomLevel: 'Remembering',
      points: 2,
    },
    {
      questionText: 'What type of index is physically stored in the same order as the actual table data rows?',
      questionType: 'MCQ',
      options: ['Clustered Index', 'Non-Clustered Index', 'Bitmap Index', 'Hash Index'],
      correctAnswer: 0,
      explanation: 'A Clustered Index dictates the physical storage order of rows in a table on disk. Hence, a table can have only one clustered index.',
      bloomLevel: 'Analyzing',
      points: 2,
    },
  ],
  'data structures': [
    {
      questionText: 'What is the worst-case time complexity of searching an element in a balanced Binary Search Tree (such as AVL or Red-Black Tree)?',
      questionType: 'MCQ',
      options: ['O(1)', 'O(log N)', 'O(N)', 'O(N log N)'],
      correctAnswer: 1,
      explanation: 'A balanced BST guarantees a height of O(log N), so search, insertion, and deletion all run in O(log N) worst-case time.',
      bloomLevel: 'Understanding',
      points: 2,
    },
    {
      questionText: 'Which data structure is primarily used to implement Breadth-First Search (BFS) graph traversal?',
      questionType: 'MCQ',
      options: ['Stack', 'Queue (FIFO)', 'Priority Queue', 'Disjoint Set (Union-Find)'],
      correctAnswer: 1,
      explanation: 'BFS explores vertices level by level, requiring a FIFO Queue data structure to order vertex exploration.',
      bloomLevel: 'Applying',
      points: 2,
    },
    {
      questionText: 'What is the average time complexity of QuickSort?',
      questionType: 'MCQ',
      options: ['O(N)', 'O(N log N)', 'O(N^2)', 'O(log N)'],
      correctAnswer: 1,
      explanation: 'QuickSort divides the array around a pivot, achieving O(N log N) on average, though worst case is O(N^2) with poor pivot choice.',
      bloomLevel: 'Remembering',
      points: 2,
    },
  ],
  'artificial intelligence': [
    {
      questionText: 'What activation function suffers most severely from the vanishing gradient problem during deep network backpropagation?',
      questionType: 'MCQ',
      options: ['ReLU (Rectified Linear Unit)', 'Sigmoid Function', 'Leaky ReLU', 'ELU (Exponential Linear Unit)'],
      correctAnswer: 1,
      explanation: 'Sigmoid squashes outputs to (0,1) with maximum derivative 0.25, causing gradients to diminish exponentially in deep networks.',
      bloomLevel: 'Analyzing',
      points: 2,
    },
    {
      questionText: 'In reinforcement learning, what does the discount factor (gamma) control?',
      questionType: 'MCQ',
      options: [
        'The learning rate of the optimizer',
        'The importance of future rewards versus immediate rewards',
        'The exploration versus exploitation probability (epsilon)',
        'The size of the replay buffer',
      ],
      correctAnswer: 1,
      explanation: 'Gamma (between 0 and 1) discounts distant future rewards. Values close to 0 make the agent myopic, while values close to 1 make it farsighted.',
      bloomLevel: 'Understanding',
      points: 2,
    },
    {
      questionText: 'Which search algorithm uses both path cost g(n) and heuristic estimation h(n) to find the shortest path?',
      questionType: 'MCQ',
      options: ['A* Search (f(n) = g(n) + h(n))', 'Depth-First Search (DFS)', 'Dijkstra Algorithm only', 'Minimax with Alpha-Beta Pruning'],
      correctAnswer: 0,
      explanation: 'A* search evaluates nodes by combining cost g(n) to reach the node and estimated cost h(n) from the node to the goal.',
      bloomLevel: 'Applying',
      points: 2,
    },
  ],
};

export const generateQuestions = async (req: AIGenerateRequest): Promise<GeneratedQuestion[]> => {
  const { topic, count, difficulty } = req;
  const normalizedTopic = topic.toLowerCase().trim();

  let matchedBank: GeneratedQuestion[] = [];
  for (const [key, questions] of Object.entries(domainKnowledge)) {
    if (normalizedTopic.includes(key) || key.includes(normalizedTopic)) {
      matchedBank = questions;
      break;
    }
  }

  const generated: GeneratedQuestion[] = [];

  if (matchedBank.length > 0) {
    const shuffled = [...matchedBank].sort(() => Math.random() - 0.5);
    for (let i = 0; i < Math.min(count, shuffled.length); i++) {
      generated.push(shuffled[i]);
    }
  }

  while (generated.length < count) {
    const index = generated.length + 1;
    const synthesizedQuestion = createAlgorithmicQuestion(topic, index, difficulty);
    generated.push(synthesizedQuestion);
  }

  return generated.slice(0, count);
};

function createAlgorithmicQuestion(
  topic: string,
  index: number,
  difficulty: 'Easy' | 'Medium' | 'Hard'
): GeneratedQuestion {
  const bloomLevels: Array<'Remembering' | 'Understanding' | 'Applying' | 'Analyzing' | 'Evaluating'> = [
    'Understanding',
    'Applying',
    'Analyzing',
    'Evaluating',
    'Remembering',
  ];
  const bloom = bloomLevels[index % bloomLevels.length];

  const questionTemplates = [
    {
      text: 'In the context of ' + topic + ', what is the primary purpose and architectural significance of its core execution pipeline?',
      options: [
        'It maximizes throughput and resource isolation within the ' + topic + ' environment.',
        'It replaces standard operating system protocols without compliance checks.',
        'It limits concurrency to single-threaded sequential execution.',
        'It bypasses authentication and data validation checks for faster processing.',
      ],
      correct: 0,
      explanation: 'In ' + topic + ', standard architectural pipelines prioritize throughput, state validation, and resource isolation to guarantee stability.',
    },
    {
      text: 'When evaluating system trade-offs in ' + topic + ', which metric is prioritized for low-latency performance?',
      options: [
        'Batch throughput at the cost of high response times',
        'Tail latency (p99/p95) and minimal context-switching overhead',
        'Maximizing disk storage usage above 90%',
        'Unrestricted recursive memory allocation',
      ],
      correct: 1,
      explanation: 'Low-latency optimization in ' + topic + ' focuses on lowering percentile tail latencies and reducing cache-invalidation or context-switching penalties.',
    },
    {
      text: 'Which design pattern or strategy is recommended in ' + topic + ' to prevent race conditions during concurrent access?',
      options: [
        'Mutual exclusion (Mutex locks / Semaphores) and atomic read-modify-write operations',
        'Global unconstrained shared memory variables',
        'Disabling hardware interrupts completely across all CPU cores',
        'Random delay sleep functions between operations',
      ],
      correct: 0,
      explanation: 'Concurrency control in ' + topic + ' relies on atomic synchronization primitives, mutexes, and thread-safe data structures to prevent race conditions.',
    },
    {
      text: 'What is the most effective approach for offline recovery and resilience in modern ' + topic + ' implementations?',
      options: [
        'Write-Ahead Logging (WAL) and idempotent synchronized transaction replay',
        'Discarding uncommitted requests immediately without notification',
        'Forcing clients to restart all hardware nodes simultaneously',
        'Storing all critical state in non-persisted volatile cache',
      ],
      correct: 0,
      explanation: 'WAL and idempotent transaction reconciliation allow disconnected clients to synchronize cleanly when connectivity is re-established.',
    },
    {
      text: 'How does algorithmic complexity scale when optimizing search operations in ' + topic + '?',
      options: [
        'Logarithmic O(log N) or Constant O(1) via balanced indexing and hash tables',
        'Exponential O(2^N) under all normal operating conditions',
        'Quadratic O(N^2) for single-item lookups',
        'Strictly random non-deterministic scaling',
      ],
      correct: 0,
      explanation: 'Efficient systems utilize balanced indexes (B+ trees / Hash tables) to achieve sub-linear O(log N) or O(1) lookup times.',
    },
  ];

  const template = questionTemplates[(index - 1) % questionTemplates.length];

  return {
    questionText: template.text,
    questionType: 'MCQ',
    options: template.options,
    correctAnswer: template.correct,
    explanation: template.explanation,
    bloomLevel: bloom,
    points: difficulty === 'Hard' ? 3 : difficulty === 'Medium' ? 2 : 1,
  };
}